//! Generated API assembly bootstrap for sdkwork-invoice.
//! Regenerated by pnpm api:assembly:materialize.
//!
//! Multi-surface merges mount shared infrastructure routes once at the assembly layer
//! so `/healthz`, `/livez`, `/readyz`, and `/metrics` are not duplicated per surface.

use axum::Router;
use sdkwork_invoice_service_host::InvoiceServiceHost;
use sdkwork_web_bootstrap::{ApiAssemblyContribution, ReadinessCheck};
use sdkwork_web_core::{DomainContextInjector, HttpRouteManifest};
use std::sync::Arc;

pub type ApiAssembly = ApiAssemblyContribution;

pub struct ApiAssemblyContext {
    pub host: Arc<InvoiceServiceHost>,
    pub domain_context_injectors: Vec<Arc<dyn DomainContextInjector>>,
    pub readiness_check: Arc<dyn ReadinessCheck>,
}

pub async fn assemble_api_router(context: ApiAssemblyContext) -> Result<ApiAssembly, String> {
    let ApiAssemblyContext {
        host,
        domain_context_injectors,
        readiness_check,
    } = context;
    let mut router = Router::new();
    // Business-only router without a Web Framework layer — the consuming host
    // installs framework/security once on the combined router
    // (API_ASSEMBLY_SPEC §4/§6.1). The standalone invoice gateway uses the
    // framework-wrapped `gateway_mount_business` profile directly.
    router = router.merge(sdkwork_routes_invoice_app_api::build_invoice_app_router(host));
    let mut routes = Vec::new();
    routes.extend_from_slice(sdkwork_routes_invoice_app_api::gateway_route_manifest().routes());
    ApiAssemblyContribution::from_manifest(
        "sdkwork-invoice",
        "SDKWork invoice API",
        router,
        HttpRouteManifest::from_owned_routes(routes),
        domain_context_injectors,
        readiness_check,
    )
}

pub async fn assemble_app_api_contribution(
    context: ApiAssemblyContext,
) -> Result<ApiAssembly, String> {
    let ApiAssemblyContext {
        host,
        domain_context_injectors,
        readiness_check,
    } = context;
    let mut router = Router::new();
    // Business-only router without a Web Framework layer — the consuming host
    // installs framework/security once on the combined router
    // (API_ASSEMBLY_SPEC §4/§6.1). The standalone invoice gateway uses the
    // framework-wrapped `gateway_mount_business` profile directly.
    router = router.merge(sdkwork_routes_invoice_app_api::build_invoice_app_router(host));
    let mut routes = Vec::new();
    routes.extend_from_slice(sdkwork_routes_invoice_app_api::gateway_route_manifest().routes());
    ApiAssemblyContribution::from_manifest(
        "sdkwork-invoice",
        "SDKWork invoice App API",
        router,
        HttpRouteManifest::from_owned_routes(routes),
        domain_context_injectors,
        readiness_check,
    )
}
