//! Generated API assembly bootstrap for sdkwork-invoice.
//! Regenerated by pnpm api:assembly:materialize.
//!
//! Multi-surface merges mount shared infrastructure routes once at the assembly layer
//! so `/healthz`, `/livez`, `/readyz`, and `/metrics` are not duplicated per surface.

use axum::Router;
use sdkwork_invoice_service_host::InvoiceServiceHost;
use std::sync::Arc;

pub struct ApiAssembly {
    pub router: Router,
}

pub async fn assemble_api_router_from_env() -> Result<ApiAssembly, String> {
    let host = Arc::new(InvoiceServiceHost::from_env().await?);
    Ok(assemble_api_router(host).await)
}

pub async fn assemble_api_router(host: Arc<InvoiceServiceHost>) -> ApiAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_invoice_app_api::gateway_mount(host).await);
    ApiAssembly { router }
}
