-- SDKWork invoice consolidated initialization baseline (sqlite)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/sqlite/0001_invoice_baseline.sql
-- sdkwork:migration
-- id: 0001_invoice_tables
-- engine: sqlite
-- module: invoice
-- purpose: Invoice title, header, and line-item tables owned by sdkwork-invoice
-- reversible: true
-- transactional: true

CREATE TABLE IF NOT EXISTS commerce_invoice_title (
    id TEXT PRIMARY KEY NOT NULL,
    tenant_id TEXT NOT NULL,
    owner_user_id TEXT NOT NULL,
    title_type TEXT NOT NULL,
    name TEXT NOT NULL,
    tax_no TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_commerce_invoice_title_owner
    ON commerce_invoice_title (tenant_id, owner_user_id);

CREATE TABLE IF NOT EXISTS commerce_invoice (
    id TEXT PRIMARY KEY NOT NULL,
    tenant_id TEXT NOT NULL,
    organization_id TEXT,
    owner_user_id TEXT NOT NULL,
    order_id TEXT NOT NULL,
    payment_id TEXT NOT NULL,
    title_id TEXT NOT NULL,
    status TEXT NOT NULL,
    invoice_no TEXT,
    invoice_code TEXT,
    document_url TEXT,
    created_at TEXT NOT NULL,
    issued_at TEXT,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_commerce_invoice_owner
    ON commerce_invoice (tenant_id, owner_user_id, status);

CREATE INDEX IF NOT EXISTS idx_commerce_invoice_tenant_order
    ON commerce_invoice (tenant_id, order_id);

CREATE TABLE IF NOT EXISTS commerce_invoice_item (
    id TEXT PRIMARY KEY NOT NULL,
    tenant_id TEXT NOT NULL,
    invoice_id TEXT NOT NULL,
    order_item_id TEXT,
    title TEXT NOT NULL,
    amount TEXT NOT NULL,
    tax_amount TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_commerce_invoice_item_invoice
    ON commerce_invoice_item (tenant_id, invoice_id);
