[package]
rust-version.workspace = true
name = "sdkwork-invoice-service-host"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true


[lints]
workspace = true
[lib]
path = "src/lib.rs"

[dependencies]
sdkwork-database-sqlx.workspace = true
sdkwork-database-spi.workspace = true
sdkwork-invoice-database-host.workspace = true
